#服务器监听
server:
  address: localhost
  port: 8000

#数据源
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123456
  http:
    encoding:
      force: true
#分页
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodArguments: true
  params: count=countSql

#日志和时间
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  #type-handlers-package: org.cdjavaer.learning.mybatis.type